name: MerlyMentor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MM_KEY: ${{ secrets.MM_KEY }}

jobs:
  inference:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-13]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install MerlyMentor (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "::add-mask::${{ secrets.MM_KEY }}"
        mkdir -p ../../MM-Install
        cd ../../MM-Install
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/merly-ai/MPCC-Universal/main/install.sh)" -- -k "$MM_KEY"

    - name: Install MerlyMentor (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "::add-mask::${{ secrets.MM_KEY }}"
        New-Item -ItemType Directory -Force -Path "..\..\MM-Install"
        Set-Location "..\..\MM-Install"
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/merly-ai/MPCC-Universal/main/install.sh)" -- -k "$env:MM_KEY"