name: MerlyMentor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  MM_KEY: ${{ secrets.MM_KEY }}

jobs:
  inference:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-13]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Install MerlyMentor
      run: |
        echo "::add-mask::${{ secrets.MM_KEY }}"
        mkdir -p ../../MM-Install
        cd ../../MM-Install
        curl -fsSL https://raw.githubusercontent.com/merly-ai/MPCC-Universal/main/install.sh | bash -s -- -q -k "$MM_KEY"